spring:
  application:
    name: gateway-client
  cloud:
    gateway:
      routes:
        - id: route_service_one
          uri: http://localhost:9000 # uri以lb://开头（lb代表从注册中心获取服务），后面接的就是你需要转发到的服务名称
          predicates:
            - Path=/hello

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
  instance:
    prefer-ip-address: true